---
- hosts: all
  become: yes
  roles:
    - common

- hosts: lsf_master
  become: yes
  roles:
    - master

- hosts: lsf_compute
  become: yes
  roles:
    - compute

- hosts: all
  become: yes
  roles:
    - lsfinstall
